services:
  # Сервис базы данных PostgreSQL
  db:
    image: postgres:17-alpine # Используем легковесный образ
    container_name: microblog_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/ # Volume для сохранения данных БД
    env_file:
      - .env # Загружаем переменные из .env (POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB)
    ports:
      # Маппим порт 5433 хоста на 5432 контейнера, чтобы не конфликтовать с локальным Postgres
      - "5433:5432"
    environment:
      # Эти переменные используются Postgres для инициализации БД при первом запуске
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"] # Экранируем $ для shell
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s # Даем время на запуск Postgres перед первой проверкой
    restart: unless-stopped
    networks:
      - microblog_network

  # Сервис приложения FastAPI
  web:
    build: . # Собираем образ из Dockerfile в текущей директории
    container_name: microblog_web
    volumes:
      # Монтируем код для live reload (удобно для разработки, можно убрать для чистого production)
#      - ./src:/app/src
#      - ./alembic:/app/alembic
#      - ./alembic.ini:/app/alembic.ini
      # Volume для сохранения загруженных медиафайлов
      - media_volume:/src/static/media
    ports:
      - "8000:8000" # Маппим порт 8000 хоста на 8000 контейнера
    env_file:
      - .env # Передаем все переменные окружения из .env в приложение
    depends_on:
      db:
        condition: service_healthy # Запускаем web только после того, как db станет 'healthy'
    restart: unless-stopped
    networks:
      - microblog_network

networks:
  microblog_network:
    driver: bridge

volumes:
  postgres_data: # Том для данных PostgreSQL
    driver: local
  media_volume: # Том для медиафайлов
    driver: local