apiVersion: 1

# Список источников данных для удаления (если они существуют с таким именем и orgId)
# Полезно, чтобы гарантировать применение именно нашей конфигурации
deleteDatasources:
  - name: Prometheus
    orgId: 1

# Список источников данных для создания или обновления
datasources:
    # Имя источника данных, которое будет отображаться в Grafana UI
  - name: Prometheus
    # Тип источника данных
    type: prometheus
    # Режим доступа. 'proxy' означает, что браузер пользователя будет делать запросы к Grafana,
    # а Grafana уже будет запрашивать данные у Prometheus. 'direct' означал бы,
    # что браузер пользователя напрямую обращается к Prometheus.
    access: proxy
    # ID организации. По умолчанию 1 для стандартной организации Grafana.
    orgId: 1
    # URL, по которому Grafana будет обращаться к Prometheus.
    # Используем имя сервиса 'prometheus' и его стандартный порт 9090 внутри сети Docker.
    url: http://prometheus:9090
    # Отключить базовую аутентификацию (если Prometheus не требует логин/пароль)
    basicAuth: false
    # Сделать этот источник данных источником по умолчанию для новых панелей.
    isDefault: true
    # Позволять ли пользователям редактировать этот источник данных через UI Grafana.
    editable: true
    # Версия JSON данных (для внутреннего использования Grafana)
    jsonData:
      # Таймаут для HTTP запросов к Prometheus
      timeout: 60