global:
  scrape_interval: 15s # Как часто собирать метрики
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'fastapi_app'
    # Используем DNS Docker Compose для обнаружения сервиса web
    # Prometheus будет опрашивать этот адрес
    static_configs:
      - targets: [ 'web:8000' ] # Имя сервиса и порт FastAPI внутри сети Docker